project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projetos
        menu:       
        - href: projects/segmentation/segmentation.qmd
          text: Segmentação de clientes com Machine Learning
        - href: projects/churn/churn.qmd
          text: Redução da taxa de churn  
        - href: projects/realestate/realestate.qmd
          text: Oportunidades em Real Estate (Zillow, EUA) 
        #- href: projects/maximizing_sales/maximizing_sales.qmd
        #  text: Maximizando a receita em uma coffee store    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-fold: false
    code-block-bg: true
    code-block-border-left: false
    code-line-numbers: false
    highlight-style: haddock