project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: segmentation.qmd
        text: Segmentação de clientes
      - href: realestate.qmd
        text: Oportunidades em Real Estate (Zillow, EUA)   
      - href: churn.qmd
        text: Análise de churn     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-fold: false
    code-block-bg: true
    code-block-border-left: false
    code-line-numbers: false
    highlight-style: haddock



